let reload=document.querySelector(".reload");
let mssgcontainer=document.querySelector(".mssgcontainer")
let mssg=document.querySelector("#mssg")
let hidemssg=document.querySelector(".hidemssg");
let arr=["Why don’t skeletons fight each other? They don’t have the guts.",
"I told my wife she was drawing her eyebrows too high. She looked surprised.",
"Why don’t eggs tell jokes? They’d crack each other up.",
"What do you call fake spaghetti? An impasta.",
"I would avoid the sushi if I was you. It’s a little fishy.",
"Why don’t scientists trust atoms? Because they make up everything.",
"Why did the scarecrow win an award? Because he was outstanding in his field.",
"Why don’t skeletons fight? They don’t have the guts.",
"I’m reading a book on anti-gravity. It’s impossible to put down.",
"What do you call cheese that isn’t yours? Nacho cheese.",
"How does a penguin build its house? Igloos it together.",
"What do you call a factory that makes okay products? A satisfactory.",
"What do you call a bear with no teeth? A gummy bear.",
"What’s orange and sounds like a parrot? A carrot.",
"Why was the math book sad? It had too many problems.",
"What do you call an alligator in a vest? An investigator.",
"Why couldn’t the bicycle stand up by itself? It was two tired.",
"Why don’t vampires go to barbecues? They don’t like stakes.",
"What do you get when you cross a snowman with a vampire? Frostbite.",
"Why did the golfer bring two pairs of pants? In case he got a hole in one.",
"Why was the tomato blushing? Because it saw the salad dressing.",
"What do you call a boomerang that won’t come back? A stick.",
"Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
"How do you organize a space party? You planet.",
"What kind of shoes do ninjas wear? Sneakers.",
"What do you call a dog magician? A labracadabrador.",
"Why did the picture go to jail? Because it was framed.",
"Why did the student eat his homework? Because the teacher said it was a piece of cake.",
"Why don’t oysters donate to charity? Because they’re shellfish.",
"Why was the music teacher so good at baseball? He had perfect pitch.",
"Why couldn’t the leopard play hide and seek? Because he was always spotted.",
"What do you call a cow with no legs? Ground beef.",
"What do you call a pile of cats? A meowtain.",
"Why did the melon jump into the lake? It wanted to be a water-melon.",
"Why was the belt arrested? It held up a pair of pants.",
"Why are fish so smart? Because they live in schools.",
"What do you call an elephant that doesn’t matter? An irrelephant.",
"What kind of tree fits in your hand? A palm tree.",
"Why did the bicycle fall over? Because it was two tired.",
"What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
"Why was the math teacher late? She took the rhombus.",
"Why do bees have sticky hair? Because they use honeycombs.",
"Why couldn’t the pirate finish his alphabet? He got lost at C.",
"What do you call a sleeping bull? A bulldozer.",
"What did the janitor say when he jumped out of the closet? Supplies!",
"What’s a balloon’s least favorite type of music? Pop.",
"Why did the chicken go to the séance? To talk to the other side.",
"Why don’t koalas count as bears? They don’t have the right koalafications.",
"Why was the stadium so cold? It was filled with fans.",
"What do you call a bear in the rain? A drizzly bear.",
"What did the ocean say to the beach? Nothing, it just waved.",
"Why did the scarecrow become a successful motivational speaker? He was outstanding in his field.",
"Why don’t we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
"What did the big flower say to the little flower? Hi, bud!",
"Why did the computer go to the doctor? It had a virus.",
"What do you call a fish with no eyes? Fsh.",
"Why was the broom late? It swept in.",
"Why don’t crabs give to charity? Because they’re shellfish.",
"What do you call a snowman’s dog? A slush puppy.",
"Why do cows have hooves instead of feet? Because they lactose.",
"What’s a skeleton’s favorite instrument? The trombone.",
"What do you call a sleeping dinosaur? A dino-snore.",
"Why did the computer break up with the keyboard? It just couldn’t connect anymore.",
"Why are ghosts bad liars? Because you can see right through them.",
"What did one hat say to the other? Stay here, I’m going on ahead.",
"What’s a tree’s favorite drink? Root beer.",
"Why was the cookie sad? Because his friends were all crumby.",
"What did the buffalo say to his son when he left? Bison.",
"What’s brown and sticky? A stick.",
"Why was Cinderella so bad at basketball? She kept running away from the ball.",
"Why don’t mountains get tired? They’re always resting.",
"Why are spiders great web developers? Because they’re great at finding bugs.",
"Why don’t jokes about elevators ever get old? They work on so many levels.",
"What’s a pirate’s favorite letter? You’d think it’s R, but it’s the C!",
"What’s faster, hot or cold? Hot, because you can catch a cold.",
"Why can’t you trust stairs? They’re always up to something.",
"What do you get when you cross a vampire and a snowman? Frostbite.",
"Why did the tomato turn red? Because it saw the salad dressing.",
"What did the fisherman say to the magician? Pick a cod, any cod.",
"Why don’t kleptomaniacs play cards? They’re afraid of getting caught.",
"Why did the banana go to the doctor? It wasn’t peeling well.",
"Why don’t frogs get stressed? They eat whatever bugs them.",
"Why did the cow go to outer space? To see the Milky Way.",
"Why was the pencil confused? It lost its point.",
"What kind of streets do ghosts haunt? Dead ends.",
"Why don’t melons get married? Because they cantaloupe.",
"What do you call a snowman with a six-pack? The abdominal snowman.",
"Why was the banker so good at his job? He knew the value of a good investment.",
"Why was the calendar so popular? It had so many dates.",
"Why do golfers bring extra socks? In case they get a hole in one.",
"Why don’t birds use social media? They don’t want to tweet too much."];

const show=()=>{
    let randomindex=Math.ceil(Math.random()*(arr.length));
    mssgcontainer.classList.remove("hide");
    mssgcontainer.computedStyleMap.display="block";
    mssg.innerText=arr[randomindex];
}
const hide=()=>{
    mssgcontainer.classList.add("hide");
}
reload.addEventListener("click",show);
hidemssg.addEventListener("click",hide);
